### ISSUE TITLE
Recipe to migrate JUnit 5 assertions to AssertJ

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-testing-frameworks#8]
AssertJ is a popular Java library that provides a fluent API for expressing test assertions.

This issue will track the progress of a recipe to migrate JUnit assertions to AssertJ.

### JUnit 5 -> AssertJ 

- [x] assertTrue() ->   assertThat().isTrue() #7 
- [x] assertFalse() -> assertThat().isFalse() #13
- [x] assertEquals() -> assertThat().isEqualTo() #13
- [x] assertNotEquals() -> assertThat().isNotEqualTo() #15
- [x] assertNotNull() -> assertThat().isNotNull() #18
- [x] assertIsNull() -> assertThat().isNull() #18
- [x] assertArrayEquals() -> assertThat().containsExactly() #15
- [x] assertSame() -> assertThat().isSameAs() #21
- [x] fail() -> Assertions.fail()
- [x] Maven visitor that adds AssertJ dependency
- [x] Define JUnit Assertions -> AssertJ Recipe
- [ ] Add tutorial page for migrating JUnit asserts to AssertJ

**Comment by sambsnyd** [comment]
@tkvangorder @SofiaBrittoSchwartz I snuck into this issue and added check boxes for updating the docs and adding an integration test with the junit 4 -> 5 recipe. Here's [an example](https://github.com/openrewrite/rewrite-testing-frameworks/blob/9e6d5b6b1efc0e7f9b71bbb5272fd1e2d9ab5222/src/test/kotlin/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.kt#L30) of such a test class. The goal is to ensure that someone could start with a pure JUnit 4 project and run both recipes at once to get a JUnit 5 project with AssertJ assertions in one go.

**Comment by sambsnyd** [comment]
Since all that's left is docs we'll track that part here and consider this done
https://github.com/openrewrite/rewrite-docs/issues/53
